---
name: multiple-jobs

on:
  workflow_dispatch: ~
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: "job-1-step-1"
        run: echo 'step 1'

  job-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "job-2-step-1"
        run: echo 'step 1'

  job-3:
    runs-on: ubuntu-latest
    steps:
      - name: "job-3-step-1"
        run: echo 'step 1'
      
  job-4:
    runs-on: ubuntu-latest
    steps:
      - name: "job-4-step-1"
        run: echo 'step 1'

  job-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "job-5-step-1"
        run: echo 'step 1'

  job-6:
    runs-on: ubuntu-latest
    steps:
      - name: "job-6-step-1"
        run: echo 'step 1'
